# Generated by Django 3.2 on 2023-03-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230310_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
