# Generated by Django 3.2 on 2023-03-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_animals_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
